version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: STOCK_INFOR_DB
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword!2025
    ports:
      - 1444:1433
    volumes:
      - C:\Users\pc\Visual Studio Code\Docker\SQL_DB_STOCK_DATA:\var\opt\mssql\db_data
    restart: always
    mem_limit: 1g
    memswap_limit: 2g
